typography_spectrum: 0.57395
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.90336
analytics:
  google: null
  facebook: null
  twitter: null
name: DNC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: DN's
description: Photo Portfolio
purpose: []
